- name: Install python-pycurl and python-apt
  apt: pkg={{ item }} update_cache=yes state=present
  with_items:
   - python-pycurl
   - python-apt

- name: Enable Logstash repository
  apt_repository: repo="deb http://packages.elasticsearch.org/logstash/{{ logstash_version }}/debian stable main" state=present

- name: Add Logstash repo key
  apt_key: url="http://packages.elasticsearch.org/GPG-KEY-elasticsearch" state=present

- name: Install Logstash from repository
  apt: pkg={{ item }} update_cache=yes state=present
  with_items:
   - logstash
   - logstash-contrib

- name: Adjust init.d permissions
  lineinfile: dest=/etc/init.d/logstash regexp="^LS_USER=" line="LS_USER=root" state=present backup=yes

- name: Adjust init.d permissions
  lineinfile: dest=/etc/init.d/logstash regexp="^LS_GROUP=" line="LS_GROUP=root" state=present backup=yes

- name: Create Logstash Redis input configuration
  template: src=test-logstash.conf.j2 dest="/etc/logstash/conf.d/test-logstash.conf" owner=root group=root mode=0644
  notify:
   - restart logstash
